### ISSUE TITLE
Code donation

### ISSUE THREAD

**Issue by HClausing** [SaifAqqad/AspireRunner#23]
Hello,

Thanks and congratulations for this nice project.

Nowadays I'm writing some kind of Aspire Resource Server for production usage, to send data to .NET Aspire Dashboard (in Standalone mode), allowing to see the Resources page and control every service, as .NET Aspíre does today, but only for development scenario.

It's something like they did on this discussion: https://github.com/dotnet/aspire/discussions/4440

But I'm looking for a way to add some deploy, like download services/resources packages from nuget or another source, and install on target server, and I saw your Nuget helper that can help a lot on the project. I'm requesting a donation from this piece of code, if you don't mind.

I've sent you an invite for the repository, if you have interest. Now it's private, but when it's more robust, I'm intend to change to public and apply MIT licence for everyone usage.

Thanks.

**Comment by SaifAqqad** [comment]
I'm glad you found it helpful for your project :)

Most of my repositories (including this one) are completely free and open source ([License](https://github.com/SaifAqqad/AspireRunner/blob/main/LICENSE)) so you're free to use whatever you want from it without limitations.

Anyway, I've accepted the invite and will try my best to help you with the project as it sounds really useful and interesting

**Comment by HClausing** [comment]
> I'm glad you found it helpful for your project :)
> 
> Most of my repositories (including this one) are completely free and open source ([License](https://github.com/SaifAqqad/AspireRunner/blob/main/LICENSE)) so you're free to use whatever you want from it without limitations.
> 
> Anyway, I've accepted the invite and will try my best to help you with the project as it sounds really useful and interesting

Thank you so much!
