### ISSUE TITLE
'--https' argument doesn't work in the CLI

### ISSUE THREAD

**Issue by ryken2013** [SaifAqqad/AspireRunner#3]
Hi, it seem the '--https' or '-s' arguemnt would not work that it always use HTTPS.

Any idea for this issue?

![image](https://github.com/SaifAqqad/AspireRunner/assets/5669232/99bc29a8-a403-411c-a8b9-bc8b137300f4)

**Comment by SaifAqqad** [comment]
This has already been fixed in ef68de3565e67318064a64b16a67ec76213a9043

I will make a new release this weekend

**Comment by ryken2013** [comment]
Thanks for you quick response and greate job for this project!
