### ISSUE TITLE
Unable to configure HTTPS endpoint error with http only configuration

### ISSUE THREAD

**Issue by OndrejMus** [SaifAqqad/AspireRunner#9]
Hello,
I have received error below when running ASP.Net Core minimal API with dashboard in environment without any https certificate. I have tried to configure dashboard to not use any https and I'm wondering if it still should require any certificate in this situation. My API is hosted on IIS and there is no HTTPS binding.

Error message
`Unhandled exception. System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.`

Configuration:
```
"AspireDashboard": {
    "ApplicationName": "MsgParserAspire",
    "Otlp": {
      "EndpointUrl": "http://localhost:4317",
      "HttpEndpointUrl": "http://localhost:4318"
    },
    "Frontend": {
      "FrontendOptions": "http://localhost:18889"
    },
    "Runner": {
      "PipeOutput": false,
      "LaunchBrowser": false,
      "AutoDownload": true,
      "SingleInstanceHandling": "ReplaceExisting"
    }
  }
```

Thanks for good project :)

**Comment by SaifAqqad** [comment]
I just tested your config and it worked just fine.

Make sure you're binding the configuration correctly when calling `AddAspireDashboard`, i.e.
```csharp
builder.Services.AddAspireDashboard(options => builder.Configuration.GetSection("AspireDashboard").Bind(options));
```

**Comment by OndrejMus** [comment]
Thanks for reply. I think I found it. There was a wrong name for EndpointUrl in config json so default value with https was used. I have to yet test it in another environment without certificate, but this explains it perfectly.

Updated json if anyone would like to skip manual creation:
```
"AspireDashboard": {
  "ApplicationName": "AspireDashboard",
  "Otlp": {
    "EndpointUrl": "http://localhost:4317",
    "HttpEndpointUrl": "http://localhost:4318"
  },
  "Frontend": {
    "EndpointUrls": "https://localhost:18888;http://localhost:18889;"
  },
  "Runner": {
    "PipeOutput": false,
    "LaunchBrowser": false,
    "AutoDownload": true,
    "SingleInstanceHandling": "ReplaceExisting"
  }
}
```
